-- T-SCENE-SQL01: system scenes and role-scene mappings
-- Generated from frontend/src/data/roles.js and reviewed mapping.
-- Draft only: do not execute without human review.

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `prompt_scenes` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `scene_id` VARCHAR(64) UNIQUE NOT NULL,
  `scene_name` VARCHAR(32) NOT NULL,
  `scene_desc` VARCHAR(255) NOT NULL,
  `sort_order` INT NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `agent_template_scenes` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `role_id` VARCHAR(128) NOT NULL,
  `scene_id` VARCHAR(64) NOT NULL,
  `sort_order` INT NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY `uniq_role_scene` (`role_id`, `scene_id`),
  KEY `idx_agent_template_scenes_scene_id` (`scene_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `prompt_scenes` (`scene_id`, `scene_name`, `scene_desc`, `sort_order`) VALUES
  ('content_creation', '内容创作', '写文章、脚本、报告、提案、文档、课程材料等内容', 1),
  ('growth_conversion', '获客转化', '做流量、曝光、广告、销售开发、客户转化', 2),
  ('research_analysis', '调研分析', '查资料、看数据、做市场、用户、财务、竞品或学术分析', 3),
  ('planning_strategy', '规划决策', '定战略、做方案、排优先级、定预算、做路线图', 4),
  ('product_development', '产品开发', '写代码、做系统、搭架构、开发产品或技术方案', 5),
  ('design_experience', '设计体验', '做UI、UX、品牌、视觉、图像、无障碍体验', 6),
  ('quality_risk', '质检风控', '做测试、审查、安全、风控、合规把关', 7),
  ('operations_delivery', '运营交付', '管流程、管项目、管资源、推动执行落地', 8)
ON DUPLICATE KEY UPDATE
  `scene_name` = VALUES(`scene_name`),
  `scene_desc` = VALUES(`scene_desc`),
  `sort_order` = VALUES(`sort_order`);

INSERT INTO `agent_template_scenes` (`role_id`, `scene_id`, `sort_order`) VALUES
  ('growth-hacker', 'growth_conversion', 1),
  ('growth-hacker', 'research_analysis', 2),
  ('growth-hacker', 'planning_strategy', 3),
  ('content-creator', 'content_creation', 1),
  ('content-creator', 'growth_conversion', 2),
  ('xiaohongshu-specialist', 'growth_conversion', 1),
  ('xiaohongshu-specialist', 'content_creation', 2),
  ('xiaohongshu-specialist', 'operations_delivery', 3),
  ('douyin-strategist', 'growth_conversion', 1),
  ('douyin-strategist', 'content_creation', 2),
  ('douyin-strategist', 'operations_delivery', 3),
  ('wechat-official-account-manager', 'growth_conversion', 1),
  ('wechat-official-account-manager', 'content_creation', 2),
  ('wechat-official-account-manager', 'operations_delivery', 3),
  ('bilibili-content-strategist', 'growth_conversion', 1),
  ('bilibili-content-strategist', 'content_creation', 2),
  ('bilibili-content-strategist', 'operations_delivery', 3),
  ('weibo-strategist', 'growth_conversion', 1),
  ('weibo-strategist', 'content_creation', 2),
  ('weibo-strategist', 'operations_delivery', 3),
  ('kuaishou-strategist', 'growth_conversion', 1),
  ('kuaishou-strategist', 'content_creation', 2),
  ('kuaishou-strategist', 'operations_delivery', 3),
  ('zhihu-strategist', 'growth_conversion', 1),
  ('zhihu-strategist', 'content_creation', 2),
  ('baidu-seo-specialist', 'growth_conversion', 1),
  ('baidu-seo-specialist', 'research_analysis', 2),
  ('seo-specialist', 'growth_conversion', 1),
  ('seo-specialist', 'research_analysis', 2),
  ('social-media-strategist', 'growth_conversion', 1),
  ('social-media-strategist', 'planning_strategy', 2),
  ('social-media-strategist', 'content_creation', 3),
  ('app-store-optimizer', 'growth_conversion', 1),
  ('app-store-optimizer', 'research_analysis', 2),
  ('podcast-strategist', 'content_creation', 1),
  ('podcast-strategist', 'growth_conversion', 2),
  ('podcast-strategist', 'operations_delivery', 3),
  ('book-co-author', 'content_creation', 1),
  ('ai-citation-strategist', 'growth_conversion', 1),
  ('ai-citation-strategist', 'content_creation', 2),
  ('ai-citation-strategist', 'planning_strategy', 3),
  ('cross-border-e-commerce-specialist', 'growth_conversion', 1),
  ('cross-border-e-commerce-specialist', 'operations_delivery', 2),
  ('cross-border-e-commerce-specialist', 'planning_strategy', 3),
  ('china-market-localization-expert', 'planning_strategy', 1),
  ('china-market-localization-expert', 'research_analysis', 2),
  ('china-market-localization-expert', 'growth_conversion', 3),
  ('video-optimization-specialist', 'growth_conversion', 1),
  ('video-optimization-specialist', 'content_creation', 2),
  ('video-optimization-specialist', 'design_experience', 3),
  ('aeo-foundations-architect', 'growth_conversion', 1),
  ('aeo-foundations-architect', 'planning_strategy', 2),
  ('frontend-developer', 'product_development', 1),
  ('backend-architect', 'product_development', 1),
  ('backend-architect', 'planning_strategy', 2),
  ('mobile-app-builder', 'product_development', 1),
  ('ai-engineer', 'product_development', 1),
  ('devops-automator', 'product_development', 1),
  ('devops-automator', 'operations_delivery', 2),
  ('rapid-prototyper', 'product_development', 1),
  ('rapid-prototyper', 'planning_strategy', 2),
  ('senior-developer', 'product_development', 1),
  ('senior-developer', 'quality_risk', 2),
  ('senior-developer', 'planning_strategy', 3),
  ('security-engineer', 'quality_risk', 1),
  ('security-engineer', 'product_development', 2),
  ('code-reviewer', 'quality_risk', 1),
  ('code-reviewer', 'product_development', 2),
  ('database-optimizer', 'product_development', 1),
  ('database-optimizer', 'operations_delivery', 2),
  ('software-architect', 'product_development', 1),
  ('software-architect', 'planning_strategy', 2),
  ('site-reliability-engineer', 'product_development', 1),
  ('site-reliability-engineer', 'operations_delivery', 2),
  ('site-reliability-engineer', 'quality_risk', 3),
  ('technical-writer', 'content_creation', 1),
  ('technical-writer', 'product_development', 2),
  ('git-workflow-master', 'operations_delivery', 1),
  ('git-workflow-master', 'product_development', 2),
  ('data-engineer', 'product_development', 1),
  ('threat-detection-engineer', 'quality_risk', 1),
  ('threat-detection-engineer', 'operations_delivery', 2),
  ('autonomous-optimization-architect', 'product_development', 1),
  ('autonomous-optimization-architect', 'operations_delivery', 2),
  ('embedded-firmware-engineer', 'product_development', 1),
  ('solidity-smart-contract-engineer', 'product_development', 1),
  ('solidity-smart-contract-engineer', 'quality_risk', 2),
  ('incident-response-commander', 'operations_delivery', 1),
  ('incident-response-commander', 'quality_risk', 2),
  ('ai-data-remediation-engineer', 'quality_risk', 1),
  ('ai-data-remediation-engineer', 'product_development', 2),
  ('wechat-mini-program-developer', 'product_development', 1),
  ('ui-designer', 'design_experience', 1),
  ('ux-researcher', 'design_experience', 1),
  ('ux-researcher', 'research_analysis', 2),
  ('ux-architect', 'design_experience', 1),
  ('ux-architect', 'planning_strategy', 2),
  ('brand-guardian', 'design_experience', 1),
  ('brand-guardian', 'quality_risk', 2),
  ('visual-storyteller', 'design_experience', 1),
  ('visual-storyteller', 'content_creation', 2),
  ('whimsy-injector', 'design_experience', 1),
  ('whimsy-injector', 'content_creation', 2),
  ('image-prompt-engineer', 'design_experience', 1),
  ('image-prompt-engineer', 'content_creation', 2),
  ('inclusive-visuals-specialist', 'design_experience', 1),
  ('inclusive-visuals-specialist', 'quality_risk', 2),
  ('financial-analyst', 'research_analysis', 1),
  ('financial-analyst', 'planning_strategy', 2),
  ('tax-strategist', 'planning_strategy', 1),
  ('tax-strategist', 'quality_risk', 2),
  ('investment-researcher', 'research_analysis', 1),
  ('investment-researcher', 'planning_strategy', 2),
  ('accounting-specialist', 'operations_delivery', 1),
  ('accounting-specialist', 'quality_risk', 2),
  ('budget-planner', 'planning_strategy', 1),
  ('budget-planner', 'research_analysis', 2),
  ('risk-analyst', 'quality_risk', 1),
  ('risk-analyst', 'research_analysis', 2),
  ('risk-analyst', 'planning_strategy', 3),
  ('financial-model-builder', 'research_analysis', 1),
  ('financial-model-builder', 'planning_strategy', 2),
  ('outbound-strategist', 'growth_conversion', 1),
  ('outbound-strategist', 'planning_strategy', 2),
  ('discovery-coach', 'growth_conversion', 1),
  ('discovery-coach', 'research_analysis', 2),
  ('deal-strategist', 'growth_conversion', 1),
  ('deal-strategist', 'planning_strategy', 2),
  ('sales-engineer', 'growth_conversion', 1),
  ('sales-engineer', 'content_creation', 2),
  ('proposal-strategist', 'content_creation', 1),
  ('proposal-strategist', 'growth_conversion', 2),
  ('pipeline-analyst', 'research_analysis', 1),
  ('pipeline-analyst', 'growth_conversion', 2),
  ('account-strategist', 'growth_conversion', 1),
  ('account-strategist', 'operations_delivery', 2),
  ('account-strategist', 'planning_strategy', 3),
  ('sales-coach', 'operations_delivery', 1),
  ('sales-coach', 'content_creation', 2),
  ('product-manager', 'planning_strategy', 1),
  ('product-manager', 'research_analysis', 2),
  ('product-manager', 'product_development', 3),
  ('trend-researcher', 'research_analysis', 1),
  ('trend-researcher', 'planning_strategy', 2),
  ('feedback-synthesizer', 'research_analysis', 1),
  ('feedback-synthesizer', 'product_development', 2),
  ('sprint-prioritizer', 'planning_strategy', 1),
  ('sprint-prioritizer', 'operations_delivery', 2),
  ('sprint-prioritizer', 'product_development', 3),
  ('behavioral-nudge-engine', 'design_experience', 1),
  ('behavioral-nudge-engine', 'research_analysis', 2),
  ('behavioral-nudge-engine', 'product_development', 3),
  ('senior-pm', 'operations_delivery', 1),
  ('senior-pm', 'planning_strategy', 2),
  ('project-shepherd', 'operations_delivery', 1),
  ('studio-producer', 'operations_delivery', 1),
  ('studio-producer', 'content_creation', 2),
  ('studio-operations', 'operations_delivery', 1),
  ('experiment-tracker', 'research_analysis', 1),
  ('experiment-tracker', 'operations_delivery', 2),
  ('experiment-tracker', 'quality_risk', 3),
  ('jira-workflow-steward', 'operations_delivery', 1),
  ('support-responder', 'operations_delivery', 1),
  ('analytics-reporter', 'research_analysis', 1),
  ('analytics-reporter', 'content_creation', 2),
  ('finance-tracker', 'operations_delivery', 1),
  ('finance-tracker', 'research_analysis', 2),
  ('legal-compliance-officer', 'quality_risk', 1),
  ('legal-compliance-officer', 'operations_delivery', 2),
  ('infrastructure-manager', 'operations_delivery', 1),
  ('infrastructure-manager', 'product_development', 2),
  ('executive-communications', 'content_creation', 1),
  ('executive-communications', 'operations_delivery', 2),
  ('evidence-collector', 'quality_risk', 1),
  ('evidence-collector', 'content_creation', 2),
  ('reality-checker', 'quality_risk', 1),
  ('test-results-analyzer', 'quality_risk', 1),
  ('test-results-analyzer', 'research_analysis', 2),
  ('test-results-analyzer', 'content_creation', 3),
  ('api-validator', 'quality_risk', 1),
  ('api-validator', 'product_development', 2),
  ('performance-tester', 'quality_risk', 1),
  ('performance-tester', 'research_analysis', 2),
  ('performance-tester', 'product_development', 3),
  ('workflow-optimizer', 'operations_delivery', 1),
  ('workflow-optimizer', 'research_analysis', 2),
  ('workflow-optimizer', 'quality_risk', 3),
  ('security-auditor', 'quality_risk', 1),
  ('accessibility-tester', 'quality_risk', 1),
  ('accessibility-tester', 'design_experience', 2),
  ('anthropologist', 'research_analysis', 1),
  ('anthropologist', 'content_creation', 2),
  ('geographer', 'research_analysis', 1),
  ('historian', 'research_analysis', 1),
  ('historian', 'content_creation', 2),
  ('research-writer', 'content_creation', 1),
  ('research-writer', 'research_analysis', 2),
  ('data-scientist', 'research_analysis', 1),
  ('data-scientist', 'product_development', 2),
  ('ppc-campaign-strategist', 'growth_conversion', 1),
  ('ppc-campaign-strategist', 'planning_strategy', 2),
  ('search-query-analyst', 'growth_conversion', 1),
  ('search-query-analyst', 'research_analysis', 2),
  ('paid-media-auditor', 'quality_risk', 1),
  ('paid-media-auditor', 'research_analysis', 2),
  ('paid-media-auditor', 'growth_conversion', 3),
  ('social-ads-specialist', 'growth_conversion', 1),
  ('social-ads-specialist', 'content_creation', 2),
  ('retargeting-specialist', 'growth_conversion', 1),
  ('retargeting-specialist', 'research_analysis', 2),
  ('creative-performance-analyst', 'research_analysis', 1),
  ('creative-performance-analyst', 'growth_conversion', 2),
  ('creative-performance-analyst', 'content_creation', 3),
  ('media-budget-optimizer', 'planning_strategy', 1),
  ('media-budget-optimizer', 'research_analysis', 2),
  ('media-budget-optimizer', 'growth_conversion', 3),
  ('business-strategist', 'planning_strategy', 1),
  ('business-strategist', 'research_analysis', 2),
  ('competitive-analyst', 'research_analysis', 1),
  ('competitive-analyst', 'planning_strategy', 2),
  ('market-entry-strategist', 'planning_strategy', 1),
  ('market-entry-strategist', 'research_analysis', 2),
  ('market-entry-strategist', 'growth_conversion', 3),
  ('innovation-catalyst', 'planning_strategy', 1),
  ('innovation-catalyst', 'product_development', 2),
  ('innovation-catalyst', 'operations_delivery', 3),
  ('okr-coach', 'planning_strategy', 1),
  ('okr-coach', 'operations_delivery', 2),
  ('partnership-strategist', 'growth_conversion', 1),
  ('partnership-strategist', 'planning_strategy', 2),
  ('partnership-strategist', 'operations_delivery', 3)
ON DUPLICATE KEY UPDATE
  `sort_order` = VALUES(`sort_order`);
